version: '3'
services:
  mysql:
    image: shomaigu/mysql-database-class
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    volumes:
    - ./mysql:/var/lib/mysql

    environment:
    - MYSQL_ROOT_PASSWORD=root
    - TZ=Asia/Tokyo
    ports:
    - "3306:3306"
    restart: always
